spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:63792}
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

lotto:
  result-checker:
    lotteryRunOccurrence: "0 55 11 * * 6"
  number-generator:
    lotteryRunOccurrence: "0 0 12 * * 6"
    facade:
      count: 25
      lowerBand: 1
      upperBand: 99
    http:
      client:
        config:
          uri: http://www.randomnumberapi.com
          port: 80
          connectionTimeout: 5000
          readTimeout: 5000

jwt:
  authentication:
    secretKey: ${SECRET_KEY}
    expirationDays: 30
    issuer: lotto-backend-service

